#ifndef NOTES_H
#define NOTES_H

static const char * const notes[] =
{
	"Combat codes",
	"Refill your heart.\n\nPress the upper side of the touchscreen to execute this code.",
	"Refill your magic.\n\nPress the lower side of the touchscreen to execute this code.",
	"No more spin attack charge time with this code !",
	"Your sword will shine.\n\nThe game can be laggy",
	"Put your sticks in fire",
	"Moonjump:\n\nPress A to jump.\n\nYou can easily toogle this cheat in-game with DPAD Right.",
	"Move fast:\n\nPress X with any Stick direction to move fastly.\n\nYou can easily toogle this cheat in-game with DPAD Left.",
	"Endless carrots to bait your horse !",
	"New and untested !!!",
	"Moonjump:\n\nPress X + A to jump.\n\nNew and untested !!!",
	"New and untested !!!",
	"New and untested !!!",
	"Dungeon",
	"New and untested !!!",
	"New and untested !!!",
	"Inventory codes",
	"Misc.",
	"No more out of ammo with this infinite arrows code !",
	"Love the deku nuts ?\n\nTake some more then !",
	"Me too, when I was 5yo I loved having a stick in my hand to discover the world",
	"Make this building explode !",
	"What the hell is that design ?\n\nIt's war outside !",
	"Take this in your face !!",
	"I don't like spider man !",
	"Yeah !!!\n\nMake me rich !",
	"New and untested !!!",
	"New and untested !!!",
	"New and untested !!!",
	"Environment",
	"Time codes",
	"I wanna sleep some more !",
	"It's to hot to work !",
	"Wanna have a beer ?",
	"I don't wanna sleep...\n\nAlone ! :p",
	"New and untested !!!",
	"For the lazy guys",
	"Combat codes",
	"Be a wizard",
	"Be a great wizard",
	"Be a cat and get your 9 lifes",
	"Don't search arounf the world for what you can have in 5 seconds",
	"Be a really tough guy",
	"Equipment codes",
	"Get you kokiri's sword",
	"Be a legend !",
	"Want a broken sword ?",
	"Get you burnable shield",
	"For the love of Hyrule !!",
	"Whoaaa !!\n\nWhat a shiny shield you got !",
	"Be a lutin with this cheap suit\n\n#Tingle",
	"Be a demineur with this fire proof suit !",
	"Always wanted to be a fishman ?\n\n Be my guest !",
	"Unlock all",
	"Get 2,5 swords for the price of 1 !",
	"Get 3  shields for the price of 1",
	"Need some clothes ?",
	"Be god on earth and go defeat the evil Ganondorf",
	"Story codes",
	"Unlock all stones",
	"Unlock all medallions",
	"Fun codes",
	"Link's size",
	"Be a giant which crush everything under is feet",
	"Tired of being a laughable man ?",
	"Wanna see what's under the girl's skirt ?",
	"Jealous of mario ?",
	"New and untested !!!",
	"New and untested !!!",
};

#endif